spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/stats-database?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m

app:
  kafka:
    bookingTopic: "booking-topic"
    userTopic: "user-topic"
    kafkaGroupId: "kafka-group-id"