spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema